version: 2
updates:
  - package-ecosystem: "npm"
    directory: "../frontend"           
    schedule:
      interval: "weekly"             
    open-pull-requests-limit: 5

  - package-ecosystem: "gomod"
    directory: "../user_api"          
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "gomod"
    directory: "../chat_api"
    schedule:
      interval: "weekly"
