server:
  http_listen_port: 9080  
  log_level: debug

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/api/prom/push

scrape_configs:
  - job_name: 'docker'
    docker_sd_configs:
      - host: 'unix:///var/run/docker.sock'

    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: container_name
      - source_labels: [__meta_docker_container_name]
        target_label: job
      - source_labels: [__meta_docker_container_id]
        target_label: container_id

    static_configs:
      - targets:
          - localhost
        labels:
          job: docker-containers
          __path__: /var/lib/docker/containers/*/*.log

