apiVersion: v1
data:
  server.insecure: "true"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"server.insecure":"true"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2025-06-17T14:25:10Z","labels":{"app.kubernetes.io/name":"argocd-cmd-params-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-cmd-params-cm","namespace":"argocd","resourceVersion":"1750177667969375004","uid":"8fc278db-d84c-4aca-99b8-dae9b9e24295"}}
  creationTimestamp: "2025-06-17T14:25:10Z"
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cmd-params-cm
  namespace: argocd
  resourceVersion: "1750177739259103004"
  uid: 8fc278db-d84c-4aca-99b8-dae9b9e24295
