apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudcord
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/S7eFaNS/CloudCord.git'
    targetRevision: cloud
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
