apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-api-deployment
  labels:
    app: chat-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-api
  template:
    metadata:
      labels:
        app: chat-api
    spec:
      containers:
        - name: chat-api
          image: s7efan/chat-api:latest
          ports:
            - containerPort: 8084
              name: http
            - containerPort: 2112
              name: metrics
          env:
            - name: RABBITMQ_URI
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_URI
            - name: GCP_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: cloudcord-secrets
                  key: GCP_PROJECT_ID
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGODB_USER
            - name: MONGODB_PASS
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGODB_PASS
