apiVersion: v1
kind: Service
metadata:
  name: chat-api-service
  labels:
    app: chat-api
spec:
  selector:
    app: chat-api
  ports:
    - name: http
      protocol: TCP
      port: 8084
      targetPort: 8084
    - name: metrics
      port: 2112
      targetPort: 2112
  type: ClusterIP
