apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'user-api'
        static_configs:
          - targets: ['user-service:2112']

      - job_name: 'chat-api'
        static_configs:
          - targets: ['chat-api-service:2112']

      - job_name: 'notification-api'
        static_configs:
          - targets: ['notification-api-service:2112']
