package models

import "go.mongodb.org/mongo-driver/bson/primitive"

type User struct {
	UserID   primitive.ObjectID `bson:"_id,omitempty" json:"user_id"` // auto-generated by MongoDB
	Auth0ID  string             `bson:"auth0_id" json:"auth0_id"`
	Username string             `bson:"username" json:"username"`
}
