name: CI

on:
  push:
    branches: [ci]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1' 

      - name: Run unit tests for user_api
        working-directory: ./user_api
        run: |
          go test ./... -v -cover

      - name: Run tests for chat_api
        working-directory: ./chat_api
        run: |
          go test ./... -v -cover
  build:
    runs-on: ubuntu-latest
    needs: test
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and push frontend
        run: |
          docker build -t $DOCKERHUB_USERNAME/frontend:latest ./frontend
          docker push $DOCKERHUB_USERNAME/frontend:latest

      - name: Build and push user_api
        run: |
          docker build -t $DOCKERHUB_USERNAME/user-api:latest ./user_api
          docker push $DOCKERHUB_USERNAME/user-api:latest

      - name: Build and push chat_api
        run: |
          docker build -t $DOCKERHUB_USERNAME/chat-api:latest ./chat_api
          docker push $DOCKERHUB_USERNAME/chat-api:latest

      - name: Build and push notification_api
        run: |
          docker build -t $DOCKERHUB_USERNAME/notification-api:latest ./notification_api
          docker push $DOCKERHUB_USERNAME/notification-api:latest
