name: CI

on:
  push:
    branches: [development]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and push frontend
        run: |
          docker build -t $DOCKERHUB_USERNAME/frontend:latest ./frontend
          docker push $DOCKERHUB_USERNAME/frontend:latest

      - name: Build and push user_api
        run: |
          docker build -t $DOCKERHUB_USERNAME/user-api:latest ./user_api
          docker push $DOCKERHUB_USERNAME/user_api:latest

#      - name: Build and push file_storage_api
#        run: |
#          docker build -t $DOCKERHUB_USERNAME/file_storage_api:latest ./file_storage_api
#          docker push $DOCKERHUB_USERNAME/file_storage_api:latest

      - name: Build and push chat_api
        run: |
          docker build -t $DOCKERHUB_USERNAME/chat-api:latest ./chat_api
          docker push $DOCKERHUB_USERNAME/chat_api:latest

      - name: Build and push notification_api
        run: |
          docker build -t $DOCKERHUB_USERNAME/notification-api:latest ./notification_api
          docker push $DOCKERHUB_USERNAME/notification_api:latest
