
name: Snyk Scan

on:
  pull_request:
    branches:
      - main

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (for React frontend)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Set up Go (for backend)
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Setup Snyk CLI
        uses: snyk/actions/setup@master
        with:
          version: 'latest'

      - name: Run Snyk test on React frontend
        uses: snyk/actions/test@master
        with:
          path: ./frontend
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk test on Go backend user_api
        uses: snyk/actions/test@master
        with:
          path: ./user_api
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk test on Go backend chat_api
        uses: snyk/actions/test@master
        with: 
          path: ./chat_api 
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Monitor React frontend
        uses: snyk/actions/monitor@master
        with:
          path: ./frontend
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Monitor Go backend user_api
        uses: snyk/actions/monitor@master
        with:
          path: ./user_api
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Monitor Go backend chat_api
        uses: snyk/actions/monitor@master
        with:
          path: ./chat_api
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

