name: Snyk Scan

on:
  pull_request:
    branches:
      - main

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Snyk test on React frontend
        uses: snyk/actions/node@master
        with:
          path: ./frontend
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk test on Go backend user_api
        uses: snyk/actions/golang@master
        with:
          path: ./user_api
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk test on Go backend chat_api
        uses: snyk/actions/golang@master
        with:
          path: ./chat_api
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
