
name: Snyk Scan

on:
  pull_request:
    branches:
      - main

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (for React frontend)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Set up Go (for backend)
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Run Snyk test on React frontend
        uses: snyk/actions@v1
        with:
          command: test
          path: ./frontend
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk test on user_api backend
        uses: snyk/actions@v1
        with:
          command: test
          path: ./user_api
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk test on chat_api backend
        uses: snyk/actions@v1
        with:
          command: test
          path: ./chat_api
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Monitor React frontend
        uses: snyk/actions@v1
        with:
          command: monitor
          path: ./frontend
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Monitor user_api backend
        uses: snyk/actions@v1
        with:
          command: monitor
          path: ./user_api
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Monitor chat_api backend
        uses: snyk/actions@v1
        with:
          command: monitor
          path: ./chat_api
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

