name: SonarCloud Analysis

on:
  push:
    branches:
      - ci
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    name: Analyze with SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1'

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar


      - name: Run Go tests with coverage
        run: |
          go test -coverprofile=user_api_coverage.out ./user_api/...
          go test -coverprofile=chat_api_coverage.out ./chat_api/...

          echo "mode: set" > coverage.out
          tail -n +2 user_api_coverage.out >> coverage.out
          tail -n +2 chat_api_coverage.out >> coverage.out


      - name: Install SonarScanner
        run: |
          npm install -g sonarqube-scanner

      - name: Run SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=S7eFaNS_CloudCord \
            -Dsonar.organization=s7efans \
            -Dsonar.exclusions=frontend/**/* \
            -Dsonar.coverage.exclusions=frontend/**/* \
            -Dsonar.sources=. \
            -Dsonar.go.coverage.reportPaths=coverage.out \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN
